### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by Karbust** [osztenkurden/CS-GO-Observer-Custom-HUD#18]
I can't start, I get this error:

```
D:\LiveStream\Costum HUD\CS-GO-Observer-Custom-HUD-master>npm install   & node index.js
up to date in 1.3s
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::1337
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Object.<anonymous> (D:\LiveStream\Costum HUD\CS-GO-Observer-Custom-HUD-master\index.js:208:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

D:\LiveStream\Costum HUD\CS-GO-Observer-Custom-HUD-master>
```

I already deleted everything and tried again...

Does anyone know what to do?

Thanks

**Comment by LukasW1337** [comment]
It says right in the error code.. "Error: listen EADDRINUSE :::1337" - your port 1337 is used by something else, or is blocked for some reason.

**Comment by Karbust** [comment]
Now it's working, thanks.

But I can't start "csgo-overlay-for-custom-hud.exe", I open and nothing happens, I already tried both win32 and win64 (even though my machine is 64), tried running as admin, nothing happened...

Also created the config.json file with the server port (2626)...

**Comment by LukasW1337** [comment]
I only use the browser version, so no idea with the .exe sorry :/

**Comment by Karbust** [comment]
I tried the web version on obs and worked perfectly fine... The .exe just doesn't open...

**Comment by vtumialan** [comment]
Add the browser as a window in the obs?

**Comment by mahcyen** [comment]
for .exe, try creating a config.json file with the same folder as the exe
